# Generated by Django 4.2.4 on 2023-08-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_podcast_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='comments',
            field=models.ManyToManyField(blank=True, to='client.comment'),
        ),
    ]
