# Generated by Django 4.2.4 on 2023-08-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_podcast_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creator',
            new_name='author',
        ),
    ]
